# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(default='test', max_length=10, primary_key=True, serialize=False)),
                ('shop_or_lifeinfo', models.CharField(max_length=8, null='test')),
                ('img', versatileimagefield.fields.VersatileImageField(upload_to='img/', verbose_name='Image')),
                ('img_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LifeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='test', max_length=8)),
                ('lifeinfo_name', models.CharField(default='test', max_length=45)),
                ('img', models.CharField(blank=True, max_length=70, null=True)),
                ('branch', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('openhour', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(default='test', max_length=45)),
                ('address_url', models.CharField(default='test', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu_name', models.CharField(default='test', max_length=45)),
                ('extender_menu', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='test', max_length=8)),
                ('shop_name', models.CharField(default='test', max_length=45, unique=True)),
                ('img', models.CharField(blank=True, max_length=70, null=True)),
                ('branch', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('openhour', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delionapi.Shop', to_field='shop_name'),
        ),
    ]
