# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='test', max_length=10)),
                ('shop_or_lifeinfo', models.CharField(max_length=8, null='test')),
            ],
        ),
        migrations.CreateModel(
            name='LifeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifeinfo_name', models.CharField(default='test', max_length=45)),
                ('img', models.CharField(max_length=70, null=True)),
                ('branch', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('openhour', models.CharField(max_length=45, null=True)),
                ('address', models.CharField(default='test', max_length=45)),
                ('address_url', models.CharField(default='test', max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delionapi.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('menu_name', models.CharField(default='test', max_length=45)),
                ('extender_menu', models.CharField(max_length=45, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='test', max_length=45)),
                ('img', models.CharField(max_length=70, null=True)),
                ('branch', models.CharField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('openhour', models.CharField(max_length=45, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delionapi.Category')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delionapi.Shop'),
        ),
    ]
