# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delionapi', '0002_auto_20170704_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='lifeinfo',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='category_id',
        ),
        migrations.AddField(
            model_name='lifeinfo',
            name='category',
            field=models.CharField(max_length=8, null='test'),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(max_length=8, null='test'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='test', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delionapi.Shop', to_field='shop_name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(default='test', max_length=45, unique=True),
        ),
    ]
