# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delionapi', '0003_auto_20170704_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='lifeinfo',
            name='branch',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='lifeinfo',
            name='category',
            field=models.CharField(default='test', max_length=8),
        ),
        migrations.AlterField(
            model_name='lifeinfo',
            name='img',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='lifeinfo',
            name='openhour',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='lifeinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='extender_menu',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='branch',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(default='test', max_length=8),
        ),
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='openhour',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
