# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delionapi', '0005_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv',
            field=models.FileField(upload_to='%Y/%m/%d/datafile'),
        ),
    ]
