# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delionapi', '0006_auto_20170822_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelionapiCategory',
            fields=[
                ('category', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('shop_or_lifeinfo', models.CharField(blank=True, max_length=8, null=True)),
                ('img', models.CharField(max_length=100)),
                ('img_ppoi', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'delionapi_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DelionapiLifeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=8)),
                ('lifeinfo_name', models.CharField(max_length=45)),
                ('img', models.CharField(blank=True, max_length=70, null=True)),
                ('branch', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('openhour', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(max_length=45)),
                ('address_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'delionapi_lifeinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DelionapiMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('menu_name', models.CharField(max_length=45)),
                ('extender_menu', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delionapi_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DelionapiShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=8)),
                ('shop_name', models.CharField(max_length=45, unique=True)),
                ('img', models.CharField(blank=True, max_length=70, null=True)),
                ('branch', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('openhour', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'delionapi_shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
    ]
