# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delionapi', '0007_delionapicategory_delionapilifeinfo_delionapimenu_delionapishop_djangoadminlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
